---
- name: Install certbot
  apt: 
    name: {{ item }}
    state: present
  with_items:
    - certbot
    - python3-certbot-nginx

- name: Check if certificate already exists
  register: letsencrypt_cert
  